### ISSUE TITLE
"./goes-build -x -v -z platina-mk1-bmc.zip" failed after u-boot repo is re-cloned while "worktrees/u-boot/platina-mk1-bmc/" not being removed

### ISSUE THREAD

**Issue by arthurxiong3** [platinasystems/goes-build#3]
arthur@platina1:~/gopath/src/github/platinasystems/goes-build$ ./goes-build -x -v -z platina-mk1-bmc.zip
...
In directory worktrees/u-boot/platina-mk1-bmc (od=/home/arthur/gopath/src/github/platinasystems/goes-build): exit status 128
[]
panic: exit status 128

goroutine 1 [running]:
main.getImageInfo(0x0, 0x52e2db, 0x3, 0x53422c, 0x20, 0x531dd6, 0x17)
        /home/arthur/gopath/src/github/platinasystems/goes-build/bmc-ver.go:95 +0xd1b
main.makeVer(0x52e2d5, 0x3)
        /home/arthur/gopath/src/github/platinasystems/goes-build/bmc-ver.go:44 +0xa9
main.makeArmZipfile(0x7ffe108437e0, 0x13, 0x0, 0x0, 0x0, 0x0)
        /home/arthur/gopath/src/github/platinasystems/goes-build/main.go:331 +0x1a5
main.makeTarget(0x7ffe108437e0, 0x13)
        /home/arthur/gopath/src/github/platinasystems/goes-build/main.go:244 +0x133
main.main()
        /home/arthur/gopath/src/github/platinasystems/goes-build/main.go:267 +0x96
arthur@platina1:~/gopath/src/github/platinasystems/goes-build$ git branch
* kph-master
  master
arthur@platina1:~/gopath/src/github/platinasystems/goes-build$ git log -1
commit b7c678fb7b4d22edbb283cd142ea2e77097f9f2b
Author: Kevin Paul Herbert <kph@platinasystems.com>
Date:   Mon Feb 4 12:30:12 2019 -0800

    main: Fix incorrect dependencies

    goesBootArm -> GoesPlatinaMk1Bmc
    goesPlatinaMk1Bmc -> GoesBoot

    Found by <arthur@platinasystems.com>.

    Signed-off-by: Kevin Paul Herbert <kph@platinasystems.com>

Related commands history -
 2005  cd goes-build/
 2006  git remote add kph https://github.com/kph/goes-build.git
 2007  git fetch kph
 2008  git checkout -b kph-master remotes/kph/master
 2009  git clean -d -x -f
 2011  go build
 2013  cd ..
 2015  mv goes-bmc goes-bmc.old
 2019  git clone ssh://git@github.com/platinasystems/goes-bmc
 2020  mv u-boot u-boot.old
 2025  git clone ssh://git@github.com/platinasystems/u-boot
 2026  cd u-boot
 2027  ./goes-build -x -v -z platina-mk1-bmc.zip
 2028  cd ../goes-build
 2029  ./goes-build -x -v -z platina-mk1-bmc.zip

**Comment by arthurxiong3** [comment]
test
